services:
  user-service:
    build:
      context: ./user
    ports:
      - "8001:8001"
    volumes:
      - ./user/database.db:/app/database.db
    networks:
      - app-network
  product-service:
    build:
      context: ./product
    ports:
      - "8002:8002"
    volumes:
      - ./product/database.db:/app/database.db
    networks:
      - app-network
  order-service:
    build:
      context: ./order
    ports:
      - "8003:8003"
    volumes:
      - ./order/database.db:/app/database.db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge