name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test User Service
        run: |
          cd user
          docker build -t bentheaya/miniecomerce-user:latest .
          docker run bentheaya/miniecomerce-user:latest python manage.py test

      - name: Build and test Product Service
        run: |
          cd product
          docker build -t bentheaya/miniecomerce-product:latest .
          docker run bentheaya/miniecomerce-product:latest python manage.py test

      - name: Build and test Order Service
        run: |
          cd order
          docker build -t bentheaya/miniecomerce-order:latest .
          docker run bentheaya/miniecomerce-order:latest python manage.py test

      - name: Push images to Docker Hub
        run: |
          docker push bentheaya/miniecomerce-user:latest
          docker push bentheaya/miniecomerce-product:latest
          docker push bentheaya/miniecomerce-order:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      PATH: "/home/runner/.fly/bin:$PATH"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check tar and Git
        run: |
          echo $PATH
          which git
          git --version
          which tar
          tar --version

      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          flyctl version || { echo "flyctl installation failed"; exit 1; }
          # Debug: Verify flyctl is in PATH
          which flyctl
          ls -l /home/runner/.fly/bin/flyctl

      - name: Deploy User Service to Fly.io
        run: |
          cd user
          flyctl deploy --app miniecomerce-user --image bentheaya/miniecomerce-user:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy Product Service to Fly.io
        run: |
          cd product
          flyctl deploy --app miniecomerce-product --image bentheaya/miniecomerce-product:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy Order Service to Fly.io
        run: |
          cd order
          flyctl deploy --app miniecomerce-order --image bentheaya/miniecomerce-order:latest
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}